/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Webonise' at '27/12/17 1:13 PM' with Gradle 2.3
 *
 * @author Webonise, @date 27/12/17 1:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
